name: Deploy to EC2

on:
  push:
    branches:
      - main  # o "master" si ese es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar y desplegar en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html
            git fetch origin main
            git reset --hard origin/main